feat: storage example
Byzanteam/jet-example-projects pull request #5
Opened 2024-09-12 08:15 UTC by danewalters

2024-10-12 07:59 UTC, fahchen requested changes
这个函数改成 `dashboard`
`storage_plugin/functions/main/main.ts` -> `storage_plugin/functions/dashboard/main.ts`

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/project.json
> +          }
key 不能传上来

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/project.json
> +    "kysely-deno-postgres-dialect/": "https://deno.land/x/kysely_postgrs_js_dialect@v0.27.5/",
这个用 jsr 的

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/db.ts
> +import { getEnvOrThrow } from "https://cdn.jsdelivr.net/gh/byzanteam/breeze-js@v0.2.1/lib/runtime.ts";
这个放到 import map

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +      "https://nightly.jet.apps.jet.work/breeze/storage_plugin/development/main",
这个有 url helper，在 
https://github.com/Byzanteam/breeze-js/blob/main/lib/url.ts

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +          <form action="https://nightly.jet.apps.jet.work/breeze/storage_plugin/development/main/create" method="post" enctype="multipart/form-data" class="flex flex-col items-center gap-2">
action 用 url helper 构建

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +                    </form>
删除用 delete method，符合 RESTful 风格

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +app.get("/delete", async (ctx) => {
这个路由不是 RESTful 风格

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +app.get("/show", async (ctx) => {
路由风格有问题

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +app.post("/create", async (ctx) => {
路由风格有问题

2024-10-12 07:59 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +      bucket: "jet-storage-plugin-example",
这个做成变量

2024-10-12 08:02 UTC, shaddollxz commented on storage_plugin/functions/main/main.ts
> +                    </form>
form 的 method 不支持 delete
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/form#method

2024-10-12 08:03 UTC, shaddollxz commented on storage_plugin/functions/main/main.ts
> +app.post("/create", async (ctx) => {
和 delete 那里一样，这里只有用 post 写了

2024-10-12 08:04 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +                    </form>
用 POST 模拟 DELETE

2024-10-12 08:05 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +                    </form>
https://hono.dev/docs/middleware/builtin/method-override

2024-10-12 10:28 UTC, fahchen requested changes
添加 `README` 简单描述下这个项目是做什么的，用到了什么插件，同时说明下环境变量

2024-10-12 10:28 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +const objectUrl = buildUrl("/objects", baseUrl);
```suggestion
const objectUrl = buildUrl("/objects");
```

2024-10-12 10:28 UTC, fahchen commented on storage_plugin/functions/main/main.ts
> +const objectUrl = buildUrl("/objects", baseUrl);
这几个 url 有点重复和意义不清晰，重新整理下

2024-10-12 11:06 UTC, fahchen reviewed
1. 这个调整下 https://github.com/Byzanteam/jet-example-projects/pull/5#pullrequestreview-2363887185
2. 录屏一下使用效果

2024-10-12 11:10 UTC, danewalters commented
> 1. 这个调整下 [feat: storage example #5 (review)](https://github.com/Byzanteam/jet-example-projects/pull/5#pullrequestreview-2363887185)
> 2. 录屏一下使用效果

2024-10-12 11:12 UTC, danewalters commented
> 1. 这个调整下 [feat: storage example #5 (review)](https://github.com/Byzanteam/jet-example-projects/pull/5#pullrequestreview-2363887185)
> 2. 录屏一下使用效果

演示[demo](http://nightly.minio.apps.jet.work/api/v1/download-shared-object/aHR0cDovL2xvY2FsaG9zdDo5MDAwL2pldC1zdG9yYWdlLXBsdWdpbi1leGFtcGxlL2RlbW8ubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9TUg1OFdWWjBHU1FNWlZYRU1GVlYlMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMTExMTM3WiZYLUFtei1FeHBpcmVzPTQzMjAwJlgtQW16LVNlY3VyaXR5LVRva2VuPWV5SmhiR2NpT2lKSVV6VXhNaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpoWTJObGMzTkxaWGtpT2lKTlNEVTRWMVphTUVkVFVVMWFWbGhGVFVaV1ZpSXNJbVY0Y0NJNk1UY3lPRGMwTWpRMk5Dd2ljR0Z5Wlc1MElqb2lZV1J0YVc0aWZRLm5zdjhxNzZMcXNqTDEzZU9BUEhKX2JIMWpPbnhwdVp2ckRYeWV5Qnc1b0M0YlRjY2YzNV9SZ1lCUEFrWWFnQktKaDgtMzBpUWNYLTlwOG90ZVU3aUpBJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZ2ZXJzaW9uSWQ9bnVsbCZYLUFtei1TaWduYXR1cmU9MmE0OGM5MTJiMTY1NjZmZjlkNjdlYWFmNzBlMjFjYmUwNzk2Y2NkZTUzNTcwNTQ1YTlkYjI4YTM3NmFiY2EyYQ)

2024-10-12 11:16 UTC, fahchen requested changes

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +    )
```suggestion
    objects.map(
      (object) => {
        const objectUrl = buildUrl(`/objects/${object.id}`)

        return html`
                  <li class="flex items-center justify-between py-4 px-5 border rounded-md">
                    <div class="flex flex-col gap-1">
                      <p>ID: ${object.id}</p>
                      <p>Key: ${object.key}</p>
                    </div>
                    <div class="flex gap-2 ml-auto">
                      <form action="${objectUrl}" method="get">
                        <button type="submit" class="cursor-pointer">show</button>
                      </form>
                      <form action="${objectUrl}" method="post">
                        <input type="text" name="_method" value="DELETE" class="hidden" />
                        <button type="submit" class="cursor-pointer">delete</button>
                      </form>
                    </div>
                  </li>
                `,
    )
```

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +  const res = await fetch(`${storagePluginApi}/${id}`, {
```suggestion
  const res = await fetch(buildUrl(id, storagePluginApi), {
```

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +const exampleBaseUrlWithObject = buildUrl("/objects");
```suggestion
```

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +  const createBaseRes = await fetch(storagePluginApi, {
没懂创建存储空间是什么意思，你看下 plugin 的 api 的描述是什么

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +      method: "post",
全部用大写，全部检查一遍
```suggestion
      method: "POST",
```

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +  return ctx.json(await createBaseRes.json());
用 early return 来避免嵌套
```suggestion
  if (!createBaseRes.ok) {
    return ctx.json(await createBaseRes.json());
  }

  const createBaseData: {
    object_id: string;
    storagePluginApi: string;
    fields: object;
  } = await createBaseRes.json();

  const uploadFileForm = new FormData();

  Object.entries(createBaseData.fields).forEach(([key, value]) => {
    uploadFileForm.append(key, value);
  });

  uploadFileForm.set("file", file);

  const uploadRes = await fetch(createBaseData.storagePluginApi, {
    method: "post",
    body: uploadFileForm,
  });

  if (uploadRes.ok) {
    return ctx.redirect(exampleBaseUrl);
  } else {
    return ctx.text(await uploadRes.text());
  }
}
```

2024-10-12 11:16 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +    console.error("Error:", res);
这里打了日志，其他地方为什么没有？

2024-10-12 11:18 UTC, fahchen requested changes

2024-10-12 11:18 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +            <button type="submit" class="border rounded-md p-2 w-max">创建资源</button>
```suggestion
            <button type="submit" class="border rounded-md p-2 w-max">上传</button>
```

2024-10-14 01:57 UTC, fahchen requested changes

2024-10-14 01:57 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +  const createBaseData = await createBaseRes.json();
base 是什么意思？我之前就评论过了
https://github.com/Byzanteam/jet-example-projects/pull/5#discussion_r1797684143

2024-10-14 01:57 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +  return ctx.text(await uploadRes.text());
```suggestion
  if (uploadRes.ok) {
    return ctx.redirect(exampleBaseUrl);
  } else {
    console.error("Error:", uploadRes);
    return ctx.text(await uploadRes.text());
  }
```

2024-10-14 01:57 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +    console.error("Error:", res);
这个几个 error 给一下具体是哪个接口报错了

2024-10-14 01:59 UTC, fahchen commented on storage_plugin/functions/dashboard/main.ts
> +const exampleBaseUrl = getBaseUrl();
这个变量也删除吧，不需要提前获取，用到的时候获取就好了

2024-11-01 08:44 UTC, closed without merging